### ISSUE TITLE
Keys file

### ISSUE THREAD

**Issue by N3bTcx** [JonnoFTW/TwatBot#4]
Hello
I've added 4 lines for the `keys` file but i get

Traceback (most recent call last):
`File "twatbot.py", line 49, in <module>
    keys[j[0]] = j[1]
IndexError: list index out of range`

I have 4 lines in my `keys` file like
`consumer_key`
`consumer_secret`
`access_token_key`
`access_token_secret`

Any ideas?

**Comment by JonnoFTW** [comment]
You need to get those codes from running the scripts that come with the
python-twitter module. That is if you want to run it with twitter
functionality. Im not sure if it's possible to run it without it. You'll
need to setup an app key on twitter as well.

**Comment by N3bTcx** [comment]
Thanks Jonno
